// utils/documentEmail.jsx
// Generates the same React-PDF document used in the UI and uploads it as an email attachment.

import React from 'react';
import { pdf } from '@react-pdf/renderer';
import api from '../services/api';
import InvoicePDF from '../components/pdf/InvoicePDF';
import QuotationPDF from '../components/pdf/QuotationPDF';
import ProformaPDF from '../components/pdf/ProformaPDF';
import ReceiptPDF from '../components/pdf/ReceiptPDF';
import CreditNotePDF from '../components/pdf/CreditNotePDF';
import DeliveryNotePDF from '../components/pdf/DeliveryNotePDF';

const ENDPOINTS = {
  invoice: {
    detail: (id) => `/invoices/${id}`,
    send: (id) => `/invoices/${id}/send`,
    label: 'Invoice',
    numberKey: 'invoice_number',
  },
  quotation: {
    detail: (id) => `/quotations/${id}`,
    send: (id) => `/quotation/${id}/send`,
    label: 'Quotation',
    numberKey: 'quotation_number',
  },
  proforma: {
    detail: (id) => `/proformas/${id}`,
    send: (id) => `/proforma/${id}/send`,
    label: 'Proforma',
    numberKey: 'proforma_number',
  },
  receipt: {
    detail: (id) => `/receipts/${id}`,
    send: (id) => `/receipts/${id}/send`,
    label: 'Receipt',
    numberKey: 'receipt_number',
  },
  credit_note: {
    detail: (id) => `/credit-notes/${id}`,
    send: (id) => `/credit-notes/${id}/send`,
    label: 'Credit_Note',
    numberKey: 'credit_note_number',
  },
  delivery_note: {
    detail: (id) => `/delivery-notes/${id}`,
    send: (id) => `/delivery-notes/${id}/send`,
    label: 'Delivery_Note',
    numberKey: 'delivery_note_number',
  },
};

const safeFileNumber = (value = 'Document') =>
  String(value).replace(/[^A-Za-z0-9_-]+/g, '_');

const pdfElement = (type, documentData, settings) => {
  switch (type) {
    case 'invoice':
      return <InvoicePDF invoice={documentData} settings={settings} />;
    case 'quotation':
      return <QuotationPDF quotation={documentData} settings={settings} docType="quotation" />;
    case 'proforma':
      return <ProformaPDF quotation={documentData} settings={settings} docType="proforma" />;
    case 'receipt':
      return <ReceiptPDF receipt={documentData} settings={settings} />;
    case 'credit_note':
      return <CreditNotePDF creditNote={documentData} settings={settings} />;
    case 'delivery_note':
      return <DeliveryNotePDF deliveryNote={documentData} settings={settings} />;
    default:
      throw new Error('Unknown document type.');
  }
};

export const fetchDocumentEmailHistory = async (documentType, documentId) => {
  const response = await api.get(`/documents/${documentId}/email-history`, {
    params: { type: documentType },
  });
  return response.data?.data || [];
};

export const buildDocumentPdfAttachment = async (type, documentData, settings) => {
  const config = ENDPOINTS[type];
  if (!config || !documentData) {
    throw new Error('The document is unavailable for PDF generation.');
  }

  const number = documentData[config.numberKey] || 'Document';
  const fileName = `Otelex_${config.label}_${safeFileNumber(number)}.pdf`;
  const blob = await pdf(pdfElement(type, documentData, settings)).toBlob();

  if (!blob || blob.size === 0) {
    throw new Error('The PDF could not be generated. Please try again.');
  }

  return new File([blob], fileName, { type: 'application/pdf' });
};

/**
 * Send a document with the same PDF generated by the browser preview/download flow.
 * Supplying documentData avoids an extra request when sending from a details page.
 */
export const sendDocumentWithPdf = async ({
  documentType,
  documentId,
  documentData = null,
  recipientEmail = '',
  mailProvider = 'system',
  onStage = () => {},
}) => {
  const config = ENDPOINTS[documentType];
  if (!config) throw new Error('Unknown document type.');
  if (!documentId) throw new Error('Document ID is required.');

  onStage('preparing');

  const documentResponse = documentData
    ? null
    : await api.get(config.detail(documentId));
  const fullDocument = documentData || documentResponse.data?.data;

  const settingsResponse = await api.get('/settings');
  const settings = settingsResponse.data?.data || null;

  onStage('generating');
  const pdfAttachment = await buildDocumentPdfAttachment(documentType, fullDocument, settings);

  const formData = new FormData();
  if (recipientEmail.trim()) {
    formData.append('recipient_email', recipientEmail.trim());
  }
  formData.append('pdf_attachment', pdfAttachment, pdfAttachment.name);
  formData.append('mail_provider', mailProvider || 'system');

  onStage('sending');
  return api.post(config.send(documentId), formData);
};
